upgraded to gerrit 3.4.8
Tried to upgrade to newer version (3.5.6 to 3.8.0) to no avail.
After restoring the data, I always get error:
  [main] ERROR com.google.gerrit.pgm.Daemon : Thread main threw exception
  java.lang.NoClassDefFoundError: com/google/gerrit/extensions/restapi/AcceptsCreate